spring.application.name=task2
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#?????? ??????? ???, ????? ? ?????? ???????????? ????????? ?????????
spring.web.error.include-message=always

#????? ??????? ????? ??? livenessProbe ? readinessProbe
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#spring.mongodb.username=${MONGO_USER}
#spring.mongodb.password=${MONGO_PASSWORD}
#spring.mongodb.database=${MONGO_DB}
#spring.mongodb.host=${MONGO_HOST}
#spring.mongodb.port=27017